---
- name: "Set options in {{ zabbix_config['path'] }}"
  ansible.builtin.lineinfile:
    path: "{{ zabbix_config['path'] }}"
    owner: "{{ zabbix_config['owner'] }}"
    group: "{{ zabbix_config['group'] }}"
    mode: "{{ zabbix_config['mode'] }}"
    setype: "{{ zabbix_config['setype'] }}"
    regexp: "^{{ item['key'] }}=.*"
    line: |-
      {%- if item['value'] is sequence -%}
      {{ item['key'] }}={{ item['value'] | join(',') }}
      {%- elif item['value'] is string -%}
      {{ item['key'] }}={{ item['value'] }}
      {%- endif -%}
    insertafter: "# *{{ item['key'] }}=.*"
    # if value is empty => remove the whole line
    state: "{{ (item['value'] | length > 0) | ternary('present','absent') }}"
    validate: 'zabbix_agentd -t system.hostname -c %s'
  loop: "{{ zabbix_options | dict2items }}"
  loop_control:
    label: "{{ item['key'] }}={{ item['value'] }}"
  notify: "Restart service"
